# HW03 — Python Fundamentals

In [1]:
import numpy as np
import time

arr = np.arange(1_000_000)

start = time.time()
loop_result = [x * 2 for x in arr]
loop_time = time.time() - start

start = time.time()
vec_result = arr * 2
vec_time = time.time() - start

print(f"Loop time: {loop_time:.4f}s")
print(f"Vectorized time: {vec_time:.4f}s")

Loop time: 0.0522s
Vectorized time: 0.0028s

In [2]:
import pandas as pd
from pathlib import Path

RAW = Path("../data/raw")
df = pd.read_csv(RAW / "starter_data.csv", parse_dates=["date"])

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  10 non-null     str
 1   value     10 non-null     int64
 2   date      10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 382.0 bytes

  category  value       date
0        A     10 2025-08-01
1        B     15 2025-08-02
2        A     12 2025-08-03
3        B     18 2025-08-04
4        C     25 2025-08-05

In [3]:
print(df.describe())

grouped = df.groupby("category")["value"].agg(["mean", "sum", "count"])
grouped

           value                 date
count  10.000000                   10
mean   17.600000  2025-08-05 12:00:00
min    10.000000  2025-08-01 00:00:00
25%    12.250000  2025-08-03 06:00:00
50%    14.500000  2025-08-05 12:00:00
75%    23.250000  2025-08-07 18:00:00
max    30.000000  2025-08-10 00:00:00
std     7.381659                  NaN

               mean  sum  count
category
A         11.500000   46      4
B         15.666667   47      3
C         27.666667   83      3

In [4]:
from pathlib import Path

PROC = Path("../data/processed")
PROC.mkdir(parents=True, exist_ok=True)

grouped.to_csv(PROC / "summary.csv")
print("Saved to:", PROC / "summary.csv")

Saved to: ../data/processed/summary.csv

In [5]:
import sys
sys.path.append("../src")
from utils import get_summary_stats

stats = get_summary_stats(df)
print(stats["describe"])
print(stats["na_counts"])

           value                 date
count  10.000000                   10
mean   17.600000  2025-08-05 12:00:00
min    10.000000  2025-08-01 00:00:00
25%    12.250000  2025-08-03 06:00:00
50%    14.500000  2025-08-05 12:00:00
75%    23.250000  2025-08-07 18:00:00
max    30.000000  2025-08-10 00:00:00
std     7.381659                  NaN
category    0
value       0
date        0
dtype: int64